### ISSUE TITLE
Cannot build jam-jsclient 

### ISSUE THREAD

**Issue by iazarny** [inspire-software/yes-cart#54]
**Describe the bug**
Cannot build jam-jsclient  on fresh java and node nvs on win

**To Reproduce**
1. Clone
2. Run yes-cart>mvn clean install -PdevIntellijIDEA,derby,ftEmbededLucene,connREST,paymentAll,pricerules -DskipTests=true
3. See error

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Yes cart JAM: JS client 3.7.0-SNAPSHOT:
[INFO]
[INFO] Yes cart JAM: JS client ............................ FAILURE [ 36.525 s]
[INFO] Yes cart core: reports support DTO mapping ......... SKIPPED
[INFO] Yes cart integration: Price rules .................. SKIPPED
[INFO] Yes cart JAM: server ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  37.424 s
[INFO] Finished at: 2019-07-17T07:29:27+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (exec-npm-install) on project jam-jsclient: Command execution
failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (exec-npm-inst
all) on project jam-jsclient: Command execution failed.

**Expected behavior**
Cart is builded

**Desktop (please complete the following information):**
C:\home\igor\yes-cart>node -v
v10.16.0

C:\home\igor\yes-cart>npm -v
6.9.0

yes-cart>java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

Название ОС:                      Майкрософт Windows 8.1 для одного языка
Версия ОС:                        6.3.9600 Н/Д построение 9600
Изготовитель ОС:                  Microsoft Corporation
Параметры ОС:                     Изолированная рабочая станция
Построение ОС:                    Multiprocessor Free

**Additional context**
PYTHON !!!!  ??????

**Comment by iazarny** [comment]
The relevant part of npm debug is 

12320 verbose stack Error: node-sass@4.7.2 postinstall: `node scripts/build.js`
12320 verbose stack Exit status 1
12320 verbose stack     at EventEmitter.<anonymous> (C:\Users\Igor\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
12320 verbose stack     at EventEmitter.emit (events.js:198:13)
12320 verbose stack     at ChildProcess.<anonymous> (C:\Users\Igor\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
12320 verbose stack     at ChildProcess.emit (events.js:198:13)
12320 verbose stack     at maybeClose (internal/child_process.js:982:16)
12320 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
12321 verbose pkgid node-sass@4.7.2
12322 verbose cwd C:\home\igor\yes-cart\manager\jam-jsclient\src\main\typescript
12323 error Windows_NT 6.3.9600
12324 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Igor\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
12325 error node v10.16.0
12326 error npm  v3.10.10
12327 error code ELIFECYCLE
12328 error node-sass@4.7.2 postinstall: `node scripts/build.js`
12328 error Exit status 1
12329 error Failed at the node-sass@4.7.2 postinstall script 'node scripts/build.js'.
12329 error Make sure you have the latest version of node.js and npm installed.
12329 error If you do, this is most likely a problem with the node-sass package,
12329 error not with npm itself.
12329 error Tell the author that this fails on your system:
12329 error     node scripts/build.js
12329 error You can get information on how to open an issue for this project with:
12329 error     npm bugs node-sass
12329 error Or if that isn't available, you can get their info via:
12329 error     npm owner ls node-sass
12329 error There is likely additional logging output above.
12330 verbose exit [ 1, true ]

**Comment by iazarny** [comment]
Reasons provided below, going to check with vmbox, need some time
------------------------------------------------
1, Incorrect module deps for js-client
Fixed
[INFO] Yes cart JAM: services ............................. SUCCESS [  4.898 s]
[INFO] Yes cart JAM: JS client ............................ FAILURE [ 30.329 s]
[INFO] Yes cart core: reports support DTO mapping ......... SKIPPED
[INFO] Yes cart integration: Price rules .................. SKIPPED
[INFO] Yes cart JAM: server ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:29 min
[INFO] Finished at: 2019-07-17T18:16:45+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (exec-npm-install) on project jam-jsclient: Command execution
------------------------------------------------
2. Not sure, but by default the gulp 2.x was installed on node 10.x . That is incorrect.
So need to latest 3rd version
Fixed with npm install gulp@3.9.1 --save-dev
------------------------------------------------
3. Run npm run-script postinstall on js-client
------------------------------------------------

**Comment by iazarny** [comment]
Looks ok with node 8. Sorry
